trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "##vso[task.logissue type=error;sourcepath=TestProject1\Test1.cs;linenumber=11;columnnumber=1;code=100;]Assert.AreEqual failed. Expected:<1>. Actual:<2>."
      exit 1
    pwsh: true
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    projects: 'TestProject1'

- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\bin\**\TestProject2.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
  condition: always()